name: friends_app
description: A new Flutter project using lib_x.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  lib_x: ^0.1.3
  faker: ^2.0.0
  shimmer: ^2.0.0
  flutter_svg: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/images/
  
